# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'bitcampapp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for bitcampapp
pod 'Firebase/Core'
pod 'Firebase/Messaging'
  target 'bitcampappTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
